// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwjHb0YFHz6Rp7uoNM7MQyNdmRLgQ1njc',
    appId: '1:781278589671:web:349853f0abef72e5d86842',
    messagingSenderId: '781278589671',
    projectId: 'advmobprog-firebase-f57ef',
    authDomain: 'advmobprog-firebase-f57ef.firebaseapp.com',
    storageBucket: 'advmobprog-firebase-f57ef.firebasestorage.app',
    measurementId: 'G-PYXXF98PES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIn1-o_AJk9bfHvhlW4g1r1l9TzYMLUeE',
    appId: '1:781278589671:android:77c27a7be978c410d86842',
    messagingSenderId: '781278589671',
    projectId: 'advmobprog-firebase-f57ef',
    storageBucket: 'advmobprog-firebase-f57ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu9ioYEuw-X5r5GMN56a2FmQ_0-KkAU4M',
    appId: '1:781278589671:ios:2509ef5cdd627cdfd86842',
    messagingSenderId: '781278589671',
    projectId: 'advmobprog-firebase-f57ef',
    storageBucket: 'advmobprog-firebase-f57ef.firebasestorage.app',
    iosBundleId: 'com.example.santiagoMobile',
  );
}
